"""Template registry for Microsoft Outlook and Teams components.

Each template is a dict with the following keys:
  - name: Human-readable template name (also used as lookup key).
  - description: Short explanation shown in the component UI.
  - platform: ``"outlook"`` or ``"teams"``.
  - fields: Ordered list of placeholder names the user can map data to.
  - render: Callable ``(values: dict[str, str]) -> str`` that returns the
    formatted content.
"""

from __future__ import annotations

import html as _html
import json as _json
from typing import Any

# ---------------------------------------------------------------------------
# Outlook email templates
# ---------------------------------------------------------------------------

_OUTLOOK_TEMPLATES: list[dict[str, Any]] = [
    {
        "name": "Executive Summary Report",
        "description": "Clean email layout with title, summary, key metrics, and action items.",
        "platform": "outlook",
        "fields": ["title", "summary", "metrics", "action_items", "footer"],
        "render": lambda v: (
            "<div style='font-family:Segoe UI,sans-serif;max-width:680px;margin:auto'>"
            "<div style='background:#0078d4;color:#fff;padding:24px 32px;border-radius:8px 8px 0 0'>"
            f"<h1 style='margin:0;font-size:22px'>{_esc(v.get('title', 'Report'))}</h1>"
            "</div>"
            "<div style='padding:24px 32px;background:#fff;border:1px solid #e0e0e0'>"
            f"<p style='color:#333;font-size:15px;line-height:1.6'>{_esc(v.get('summary', ''))}</p>"
            "<hr style='border:none;border-top:1px solid #e0e0e0;margin:16px 0'/>"
            "<h2 style='color:#0078d4;font-size:16px;margin-bottom:8px'>Key Metrics</h2>"
            f"<p style='color:#333;font-size:14px;line-height:1.6'>{_esc(v.get('metrics', ''))}</p>"
            "<hr style='border:none;border-top:1px solid #e0e0e0;margin:16px 0'/>"
            "<h2 style='color:#0078d4;font-size:16px;margin-bottom:8px'>Action Items</h2>"
            f"<p style='color:#333;font-size:14px;line-height:1.6'>{_esc(v.get('action_items', ''))}</p>"
            "</div>"
            "<div style='padding:16px 32px;background:#f5f5f5;border-radius:0 0 8px 8px;"
            "border:1px solid #e0e0e0;border-top:none;font-size:12px;color:#888'>"
            f"{_esc(v.get('footer', 'Generated by Langflow'))}"
            "</div></div>"
        ),
    },
    {
        "name": "Status Update Email",
        "description": "Brief status update with project name, status, highlights, and next steps.",
        "platform": "outlook",
        "fields": ["project_name", "status", "highlights", "next_steps"],
        "render": lambda v: (
            "<div style='font-family:Segoe UI,sans-serif;max-width:680px;margin:auto'>"
            "<div style='background:#107c10;color:#fff;padding:20px 28px;border-radius:8px 8px 0 0'>"
            f"<h1 style='margin:0;font-size:20px'>📊 {_esc(v.get('project_name', 'Project'))} — Status Update</h1>"
            "</div>"
            "<div style='padding:20px 28px;background:#fff;border:1px solid #e0e0e0'>"
            "<table style='width:100%;border-collapse:collapse;font-size:14px'>"
            "<tr><td style='padding:8px 0;font-weight:600;color:#555;width:120px'>Status</td>"
            f"<td style='padding:8px 0;color:#333'>{_esc(v.get('status', ''))}</td></tr>"
            "<tr><td style='padding:8px 0;font-weight:600;color:#555'>Highlights</td>"
            f"<td style='padding:8px 0;color:#333'>{_esc(v.get('highlights', ''))}</td></tr>"
            "<tr><td style='padding:8px 0;font-weight:600;color:#555'>Next Steps</td>"
            f"<td style='padding:8px 0;color:#333'>{_esc(v.get('next_steps', ''))}</td></tr>"
            "</table></div>"
            "<div style='padding:12px 28px;background:#f5f5f5;border-radius:0 0 8px 8px;"
            "border:1px solid #e0e0e0;border-top:none;font-size:11px;color:#999'>"
            "Generated by Langflow</div></div>"
        ),
    },
    {
        "name": "Alert / Notification Email",
        "description": "High-visibility alert with severity, description, impact, and remediation.",
        "platform": "outlook",
        "fields": ["alert_title", "severity", "description", "impact", "remediation"],
        "render": lambda v: (
            "<div style='font-family:Segoe UI,sans-serif;max-width:680px;margin:auto'>"
            f"<div style='background:{_severity_color(v.get('severity', 'info'))};color:#fff;"
            "padding:20px 28px;border-radius:8px 8px 0 0'>"
            f"<h1 style='margin:0;font-size:20px'>⚠️ {_esc(v.get('alert_title', 'Alert'))}</h1>"
            f"<span style='font-size:13px;opacity:.85'>Severity: {_esc(v.get('severity', 'info'))}</span>"
            "</div>"
            "<div style='padding:20px 28px;background:#fff;border:1px solid #e0e0e0'>"
            "<h2 style='font-size:15px;color:#333;margin-top:0'>Description</h2>"
            f"<p style='font-size:14px;color:#444;line-height:1.6'>{_esc(v.get('description', ''))}</p>"
            "<h2 style='font-size:15px;color:#333'>Impact</h2>"
            f"<p style='font-size:14px;color:#444;line-height:1.6'>{_esc(v.get('impact', ''))}</p>"
            "<h2 style='font-size:15px;color:#333'>Remediation</h2>"
            f"<p style='font-size:14px;color:#444;line-height:1.6'>{_esc(v.get('remediation', ''))}</p>"
            "</div>"
            "<div style='padding:12px 28px;background:#f5f5f5;border-radius:0 0 8px 8px;"
            "border:1px solid #e0e0e0;border-top:none;font-size:11px;color:#999'>"
            "Generated by Langflow</div></div>"
        ),
    },
]

# ---------------------------------------------------------------------------
# Teams message / Adaptive Card templates
# ---------------------------------------------------------------------------

_TEAMS_TEMPLATES: list[dict[str, Any]] = [
    {
        "name": "Report Card",
        "description": "Adaptive Card with title, summary, and key-value facts for reports.",
        "platform": "teams",
        "fields": ["title", "summary", "facts"],
        "render": lambda v: _json.dumps(
            {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.4",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": v.get("title", "Report"),
                        "weight": "Bolder",
                        "size": "Large",
                        "wrap": True,
                    },
                    {
                        "type": "TextBlock",
                        "text": v.get("summary", ""),
                        "wrap": True,
                    },
                    {
                        "type": "FactSet",
                        "facts": _parse_facts(v.get("facts", "")),
                    },
                ],
            },
            indent=2,
        ),
    },
    {
        "name": "Status Card",
        "description": "Adaptive Card showing project status with color-coded indicator.",
        "platform": "teams",
        "fields": ["project_name", "status", "details", "owner"],
        "render": lambda v: _json.dumps(
            {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.4",
                "body": [
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "auto",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "📊",
                                        "size": "Large",
                                    }
                                ],
                            },
                            {
                                "type": "Column",
                                "width": "stretch",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": v.get("project_name", "Project"),
                                        "weight": "Bolder",
                                        "size": "Medium",
                                        "wrap": True,
                                    },
                                    {
                                        "type": "TextBlock",
                                        "text": f"Status: {v.get('status', 'N/A')}",
                                        "spacing": "None",
                                        "isSubtle": True,
                                        "wrap": True,
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        "type": "TextBlock",
                        "text": v.get("details", ""),
                        "wrap": True,
                    },
                    {
                        "type": "FactSet",
                        "facts": [
                            {"title": "Owner", "value": v.get("owner", "—")},
                            {"title": "Status", "value": v.get("status", "—")},
                        ],
                    },
                ],
            },
            indent=2,
        ),
    },
    {
        "name": "Simple Message",
        "description": "Plain HTML message with title and body for channel posts.",
        "platform": "teams",
        "fields": ["title", "body"],
        "render": lambda v: (
            f"<h2>{_esc(v.get('title', ''))}</h2>"
            f"<p>{_esc(v.get('body', ''))}</p>"
        ),
    },
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _esc(value: str) -> str:
    """Escape HTML special characters."""
    return _html.escape(str(value)) if value else ""


def _severity_color(severity: str) -> str:
    """Return a CSS color for a severity level."""
    mapping = {
        "critical": "#d13438",
        "high": "#da3b01",
        "medium": "#ff8c00",
        "low": "#0078d4",
        "info": "#0078d4",
    }
    return mapping.get(severity.lower(), "#0078d4")


def _parse_facts(facts_str: str) -> list[dict[str, str]]:
    """Parse a comma-separated ``key:value`` string into Adaptive Card facts.

    Example input: ``"Revenue: $1M, Users: 500, Growth: 12%"``
    """
    facts: list[dict[str, str]] = []
    if not facts_str:
        return facts
    for pair in facts_str.split(","):
        pair = pair.strip()
        if ":" in pair:
            key, value = pair.split(":", 1)
            facts.append({"title": key.strip(), "value": value.strip()})
        elif pair:
            facts.append({"title": pair, "value": ""})
    return facts


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_ALL_TEMPLATES = _OUTLOOK_TEMPLATES + _TEAMS_TEMPLATES
_TEMPLATE_MAP: dict[str, dict[str, Any]] = {t["name"]: t for t in _ALL_TEMPLATES}


def get_outlook_template_names() -> list[str]:
    """Return the display names of all Outlook templates."""
    return [t["name"] for t in _OUTLOOK_TEMPLATES]


def get_teams_template_names() -> list[str]:
    """Return the display names of all Teams templates."""
    return [t["name"] for t in _TEAMS_TEMPLATES]


def get_template(name: str) -> dict[str, Any] | None:
    """Look up a template by name.  Returns ``None`` if not found."""
    return _TEMPLATE_MAP.get(name)


def render_template(name: str, values: dict[str, str]) -> str:
    """Render a template with the given field values.

    Raises ``ValueError`` if the template name is not found.
    """
    tpl = _TEMPLATE_MAP.get(name)
    if tpl is None:
        msg = f"Template '{name}' not found."
        raise ValueError(msg)
    return tpl["render"](values)
